# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inzite Docs
email: info@inzite.dk
description: > # this means to ignore newlines until "baseurl:"
  Disse guides er lavet efter nyeste software ved skrivende stund. Da vores software aktivt udvikles
  er der derfor risiko for at enkelte dele af denne guide ikke er 100 procent up-to-date.
  Finder du en fejl eller andet som tilsyneladende ikke stemmer over ens med hvad denne guide forsøger
  at leve op til er du meget velkommen til at kontakte os.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jurs.me/lpo-docs/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: inzitemedia
github_username:  inzitemedia
brand: lpo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

include: ["_pages"]
